server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://54.153.110.248:13306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: fengshui
    password: fegnshuipassword
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 54.153.110.248 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 16379 # Redis服务器连接端口
    password: fengshui # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  mail:
    host: smtp.qq.com
    port: 587
    username: 707731655@qq.com
    password: irzklwefablbbbgd   # 注意不是邮箱密码
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    root: info
    com.macro.mall: debug

logstash:
  host: localhost
  enableInnerLog: false

alipay:
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  appId: your appId
  alipayPublicKey: your alipayPublicKey
  appPrivateKey: your appPrivateKey
  returnUrl: http://localhost:8060/#/pages/money/paySuccess
  notifyUrl:

paypal:
  client:
    id: AaTzO96lo7fBR_sJncQElIkc6Et4ieFJvD9Q1hpt49JnQxEkoVFj7jslqR8rPmji5j-lLJeACgl_Y4Oq
    secret: EG_5lqXVj2p7tQBkJeEhF7SlMiin9xa1bQpy-ahf5tNRpTt7mmIHEOTYh4CE6Y6RQ0Ao-VkpQhOi0EWg
  mode: sandbox  # 或 live



